### ISSUE TITLE
Survey/Observation Cardinality

### ISSUE THREAD

**Issue by KellyVance** [geological-survey-of-queensland/industry-report-profile#3]
One report may link to many surveys, observations, entities?
e.g. annual report for a tenure may have multiple bores, seismic, and scientific surveys and samples.

**Comment by DavidCrosswellGSQ** [comment]
This is taken from SOSA isResultOf https://www.w3.org/TR/vocab-ssn/#SOSAisResultOf
When I look at the reports that are in the reports list, there would only be one report per survey.
Worth going through the reports list and validating that.
The bores are linked by feature of interest.
Samples are linked to the survey (see survey model).
Observations and results are linked to the samples.

**Comment by DavidCrosswellGSQ** [comment]
@KellyVance please close if you are satisfied with the response.

**Comment by nicholascar** [comment]
Nothing specific I can add here sorry. I can say, generically, that its most important to get the *shape* of the models and the *class* of objects in them: `Report`, `Sample`, `Survey` etc. Cardinalities can be fiddled with easily enough and, in many cases, it may pay to err on the side of flexibility for all those cases that break convention. We can always query out outliers and deal with them, rather than forcing them in model constraints.

**Comment by KellyVance** [comment]
Closing issues as per conversation re: one survey may relate to many datasets
